/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#323c2d",
        "on-secondary": "#5b005b",
        "pixel-black": "#000000",
        "surface": "#0c1609",
        "lemon-shock": "#CCFF00",
        "on-tertiary-fixed-variant": "#5d3f3c",
        "inverse-primary": "#106e00",
        "on-secondary-fixed-variant": "#810081",
        "on-tertiary": "#442927",
        "tertiary": "#fff8f7",
        "secondary": "#ffabf3",
        "hard-shadow": "#000000",
        "on-surface-variant": "#baccb0",
        "tertiary-fixed": "#ffdad6",
        "primary-container": "#39ff14",
        "primary-fixed": "#79ff5b",
        "outline-variant": "#3c4b35",
        "on-background": "#dae6d0",
        "error": "#ffb4ab",
        "on-tertiary-container": "#7a5955",
        "on-primary-container": "#107100",
        "on-secondary-fixed": "#380038",
        "surface-variant": "#2d3828",
        "on-error": "#690005",
        "secondary-container": "#fe00fe",
        "background": "#0c1609",
        "on-primary-fixed": "#022100",
        "error-container": "#93000a",
        "tertiary-container": "#ffd3ce",
        "secondary-fixed-dim": "#ffabf3",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#293324",
        "primary-fixed-dim": "#2ae500",
        "surface-container": "#182214",
        "secondary-fixed": "#ffd7f5",
        "surface-container-highest": "#2d3828",
        "surface-container-high": "#222d1e",
        "surface-tint": "#2ae500",
        "surface-dim": "#0c1609",
        "surface-container-lowest": "#071105",
        "on-primary-fixed-variant": "#095300",
        "inverse-surface": "#dae6d0",
        "primary": "#efffe3",
        "on-tertiary-fixed": "#2c1513",
        "outline": "#85967c",
        "surface-container-low": "#141e11",
        "on-primary": "#053900",
        "tertiary-fixed-dim": "#e7bdb8",
        "deep-void": "#1A1A1A",
        "on-surface": "#dae6d0",
        "on-secondary-container": "#500050"
      },
      fontFamily: {
        "display-lg": ["Space Grotesk", "sans-serif"],
        "label-md": ["Space Grotesk", "sans-serif"],
        "body-lg": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
